import assert from 'node:assert/strict';
import {readFileSync} from 'node:fs';
import {aiMemoryForm} from '../app/ai.mjs';
import {ActivityCard} from '../app/ActivityCard.mjs';
import {mockActivities} from './activity-data.mjs';
assert.doesNotMatch(aiMemoryForm(),/OpenAI|ChatGPT|cloud_consent/);
assert.match(aiMemoryForm(),/value="PRIVATE"/);
const code=readFileSync(new URL('../app/app.mjs',import.meta.url),'utf8');
assert.match(code,/form.id==='ask'\|\|form.id==='discover'/);
assert.doesNotMatch(code,/api\('\/discovery\/web|api\('\/activities\/real|catalogue de démonstration/);
const html=ActivityCard({...mockActivities[0],name:'<script>bad</script>',price_per_person:null,start:null,end:null,source_url:'javascript:bad()'});
assert.doesNotMatch(html,/<script>|href="javascript/);assert.match(html,/Prix inconnu/);assert.match(html,/Horaire inconnu/);
console.log('PASS single search entry, unknown fields, source escaping, private memory.');
