import assert from 'node:assert/strict';
import {DeckState,readPlan,readSearch,deckSkeleton} from '../app/DateProposalDeck.mjs';
import {mockSearch} from './activity-data.mjs';
const data=readSearch(structuredClone(mockSearch));const state=new DeckState(data.proposals);
assert.equal(state.order.length,3);const first=state.current.id;
state.swipe('right');assert.ok(state.interested.has(first));assert.equal(state.index,1);
assert.equal(state.plans[first].status,'draft','A swipe must never accept a plan');
state.move(-1);assert.equal(state.index,0);state.move(-1);assert.equal(state.index,2);
state.toggle(data.proposals[0].activities[0]);state.toggle(data.proposals[1].activities[1]);
assert.equal(state.selected.size,2);assert.equal(state.selected.has('mock-expo'),true);
const snapshot=structuredClone(state.plans[data.proposals[1].id]);
const update=structuredClone(data.proposals[0]);update.activities[0].id='replacement';
state.update(update);assert.equal(state.index,2);assert.deepEqual(state.plans[snapshot.id],snapshot);
assert.equal(state.selected.has('mock-dinner'),false,'A stale replaced selection is removed');
assert.equal(state.selected.has('mock-expo'),true);
assert.throws(()=>new DeckState([data.proposals[0],data.proposals[0]]));
assert.throws(()=>readPlan({id:'bad'}));assert.throws(()=>readSearch({...data,proposals:[...data.proposals,data.proposals[0]]}));
assert.match(deckSkeleton(),/aria-busy="true"/);
console.log('PASS DateProposalDeck state: swipe interest, independent updates, cross-selection, malformed responses, loading.');
