// Generated by scripts/generate_date_contract.py. Edit Pydantic models, then regenerate.
export interface ActivityChoice {
  id: string;
  name: string;
  category: string;
  start: string | null;
  end: string | null;
  price_per_person: number | null;
  location: Location | null;
  address: string;
  tags: Array<string>;
  why: string;
  demo: boolean;
  image_url?: string | null;
  rating?: number | null;
  price_tier?: "budget" | "moderate" | "upscale" | null;
  pint_price_from_eur?: number | null;
  offer_note?: string | null;
  city?: string | null;
  source_name?: string | null;
  source_kind?: "import" | "web";
  imported_at?: string | null;
  description?: string;
  source: string;
  source_url?: string | null;
  kind?: string;
  checked_at?: string | null;
  schedule_status?: string;
  availability?: string;
  price_unit?: string;
  composable?: boolean;
}
export interface ActivityReplacement {
  activity_id_to_replace: string;
  new_constraints?: string | null;
}
export interface CompositionStats {
  candidate_count?: number;
  combos_generated?: number;
  selected_activity_ids?: Array<Array<string>>;
  rejected_count?: number;
  scoring_backend?: string;
  scoring_fallback?: string | null;
  diversity_strength?: number;
}
export interface DateComposition {
  selected_activity_ids: Array<string>;
  search_id?: string | null;
}
export interface DateSearch {
  constraints?: SearchConstraints;
  couple_id?: string | null;
  cloud_consent?: boolean;
}
export interface DateSearchResponse {
  status?: string;
  empty_reason?: string | null;
  message?: string;
  trace?: Array<SearchTrace>;
  sources?: Array<Record<string, unknown>>;
  searched_at?: string | null;
  cached?: boolean;
  activities?: Array<ActivityChoice>;
  budget_cap?: number | null;
  max_total_duration_minutes?: number;
  max_travel_time_minutes?: number;
  requested_steps?: number;
  search_id: string;
  proposals: Array<DeckPlan>;
  warnings: Array<string>;
  composition: CompositionStats;
}
export interface DeckActivity {
  id: string;
  type: string;
  name: string;
  start: string;
  end: string;
  price_per_person: number;
  location: Location;
  match_score: number;
  why: string;
  booking_url?: string | null;
  title: string;
  category: string;
  source: string;
  demo: boolean;
  description: string;
  address: string;
  [key: string]: unknown;
}
export interface DeckPlan {
  date_plan_id: string;
  start: string;
  end: string;
  estimated_total_eur: number;
  reason: string;
  activities: Array<DeckActivity>;
  id: string;
  status: "draft" | "proposed" | "accepted" | "completed" | "cancelled";
  diversity_label: string;
  duration_minutes: number;
  search_id: string;
  kept_ids: Array<string>;
  timeline: Array<TimelineEntry>;
  source: string;
  [key: string]: unknown;
}
export interface Location {
  lat: number;
  lng: number;
}
export interface SearchConstraints {
  text?: string;
  budget?: number | null;
  categories?: Array<"food" | "culture" | "concerts" | "cinema" | "outdoors" | "sport" | "workshops" | "nightlife" | "home" | "travel">;
  required_activity_id?: string | null;
  required_activity_ids?: Array<string>;
  radius_km?: number | null;
  activity_count?: number;
  max_plans?: number;
  mode?: "offline" | "openai" | "auto";
  use_shared_interests?: boolean;
  time_window?: TimeWindow | null;
  max_total_duration_minutes?: number;
  max_travel_time_minutes?: number;
}
export interface SearchTrace {
  stage: string;
  [key: string]: unknown;
}
export interface TimeWindow {
  start: string;
  end: string;
  duration_minutes?: number | null;
}
export interface TimelineEntry {
  type: "travel" | "activity";
  minutes?: number | null;
  [key: string]: unknown;
}
