"""Generate strict TS types and JSON Schema from the backend. No network dependency."""
from pathlib import Path
import argparse
import json
import sys

ROOT=Path(__file__).resolve().parents[1]
sys.path.insert(0,str(ROOT))
from backend.streams.E_orchestrator.deck_models import DeckContract


def ts(schema):
    if '$ref' in schema:return schema['$ref'].split('/')[-1]
    if 'enum' in schema:return ' | '.join(json.dumps(x) for x in schema['enum'])
    if 'const' in schema:return json.dumps(schema['const'])
    if 'anyOf' in schema:return ' | '.join(ts(x) for x in schema['anyOf'])
    kind=schema.get('type')
    if kind=='array':return f"Array<{ts(schema['items'])}>"
    if kind=='object':return 'Record<string, unknown>'
    return {'string':'string','number':'number','integer':'number','boolean':'boolean','null':'null'}.get(kind,'unknown')


def generate():
    schema=DeckContract.model_json_schema()
    lines=['// Generated by scripts/generate_date_contract.py. Edit Pydantic models, then regenerate.']
    for name,model in schema['$defs'].items():
        if model.get('type')!='object':
            lines.append(f'export type {name} = {ts(model)};');continue
        lines.append(f'export interface {name} {{')
        required=set(model.get('required',[]))
        for key,value in model.get('properties',{}).items():
            lines.append(f'  {key}{"" if key in required else "?"}: {ts(value)};')
        if model.get('additionalProperties') is True:lines.append('  [key: string]: unknown;')
        lines.append('}')
    return {
        ROOT/'frontend/contracts/date-deck.schema.json':json.dumps(schema,ensure_ascii=False,indent=2)+'\n',
        ROOT/'frontend/src/date-contract.mts':'\n'.join(lines)+'\n',
    }


if __name__=='__main__':
    parser=argparse.ArgumentParser();parser.add_argument('--check',action='store_true');args=parser.parse_args()
    for path,content in generate().items():
        if args.check:
            if not path.exists() or path.read_text(encoding='utf-8')!=content:raise SystemExit(f'Stale contract: {path.name}')
        else:
            path.parent.mkdir(parents=True,exist_ok=True);path.write_text(content,encoding='utf-8',newline='\n')
    print('DatePlan Python/TypeScript contract '+('verified' if args.check else 'generated'))
